listener 8883 0.0.0.0
protocol mqtt

cafile      /mosquitto/certs/ca.crt
certfile    /mosquitto/certs/mosquitto.crt
keyfile     /mosquitto/certs/mosquitto.key
tls_version tlsv1.3

require_certificate      true
use_identity_as_username true
allow_anonymous          false

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
